# Generated by Django 5.1.3 on 2024-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
    ]
