# Generated by Django 5.1.3 on 2024-11-19 05:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0002_alter_producto_cantidad_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='duracion_dias',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado_membresia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_inicio_membresia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='membresia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2024, 12, 18)),
        ),
        migrations.AddField(
            model_name='membresia',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='membresia',
            name='tipo',
            field=models.CharField(default='Mensual', max_length=100),
        ),
        migrations.AddField(
            model_name='membresia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gestion_VarelaGimnasio.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
