# Generated by Django 5.1.3 on 2024-11-19 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0003_remove_membresia_duracion_dias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion_VarelaGimnasio.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Compra', 'Compra')], max_length=100),
        ),
    ]
