# Generated by Django 5.1.3 on 2024-11-19 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0004_remove_transaccion_descripcion_transaccion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2024, 12, 19)),
        ),
    ]
