# Generated by Django 5.1.3 on 2024-12-04 05:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0006_alter_membresia_fecha_expiracion_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2025, 1, 2)),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='gestion_VarelaGimnasio.producto')),
            ],
        ),
    ]
