# Generated by Django 5.1.3 on 2024-12-05 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_VarelaGimnasio', '0007_alter_membresia_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2025, 1, 3)),
        ),
    ]
